redir-port: 7892
tproxy-port: 7895
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
bind-address: "*"
external-ui: "/usr/share/openclash/dashboard"
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 127.0.0.1:7874
  default-nameserver:
  - 114.114.114.114
  nameserver:
  - 114.114.114.114
  - 207.148.120.244
  fallback:
  - https://dns.cloudflare.com/dns-query
  - tls://8.8.8.8:853
proxies:
#===========VMESS
- name: "VMESS-WS"
  type: vmess
  server: v2ray.sshanda.com
  port: 443
  uuid: xxxx.xxxx.xxxx.xxxx
  alterId: 64
  cipher: auto
  udp: true
  skip-cert-verify: true
  tls: true
  servername: bug.com
  network: ws
  ws-path: /v2ray
  ws-headers:
    Host: bug.com
    
#==========TROJAN
- name: "TROJAN"
  type: trojan
  server: sg2.trojan.bonds.id
  port: 443
  password: passakun
  udp: true
  sni: bug.com
  skip-cert-verify: true
  
  
proxy-groups:
  - name: ğŸš€
    type: select
    proxies:
      - â™»ï¸
      - VMESS-WS
      - TROJAN
  - name: â™»ï¸
    type: load-balance
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - VMESS-WS
      - TROJAN
    strategy: round-robin #consistent-hashing # or round-robin
  - name: ğŸ¯
    type: select
    proxies:
      - DIRECT
      - ğŸš€
      - â™»ï¸
      
rules:
  - IP-CIDR,10.0.0.0/8,ğŸ¯,no-resolvE
  - IP-CIDR,100.64.0.0/10,ğŸ¯,no-resolve
  - IP-CIDR,127.0.0.0/8,ğŸ¯,no-resolve
  - IP-CIDR,172.16.0.0/12,ğŸ¯,no-resolve
  - IP-CIDR,192.168.0.0/16,ğŸ¯,no-resolve
  - IP-CIDR,198.18.0.0/16,ğŸ¯,no-resolve
 #MOBILE LEGENDS
  #- DOMAIN-SUFFIX,youngjoygame.com
  - DOMAIN-SUFFIX,mobilelegends.com,ğŸ¯
  - DOMAIN-SUFFIX,app.adjust.net.in,ğŸ¯
  - DOMAIN-SUFFIX,app.adjust.com,ğŸ¯
  - DOMAIN-SUFFIX,app.adjust.world,ğŸ¯
  - DOMAIN-SUFFIX,ml.CS30.NET,ğŸ¯
  - DOMAIN-SUFFIX,pv.sohu.com,ğŸ¯
  - DOMAIN-SUFFIX,yuanzhanapp.com,ğŸ¯
  - DOMAIN-SUFFIX,aihelp.net,ğŸ¯
  #Real-time-battle
  - DST-PORT,4003,ğŸ¯ 
  - DST-PORT,4004,ğŸ¯
  - DST-PORT,4014,ğŸ¯ 
  - DST-PORT,5001,ğŸ¯ 
  - DST-PORT,5002,ğŸ¯ 
  - DST-PORT,5003,ğŸ¯ 
  - DST-PORT,5004,ğŸ¯ 
  - DST-PORT,5005,ğŸ¯ 
  - DST-PORT,5006,ğŸ¯ 
  - DST-PORT,5007,ğŸ¯ 
  - DST-PORT,5008,ğŸ¯ 
  - DST-PORT,5013,ğŸ¯ 
  - DST-PORT,5014,ğŸ¯ 
  - DST-PORT,5021,ğŸ¯ 
  - DST-PORT,5023,ğŸ¯ 
  - DST-PORT,5052,ğŸ¯ 
  - DST-PORT,5053,ğŸ¯ 
  - DST-PORT,5055,ğŸ¯ 
  - DST-PORT,10003,ğŸ¯ 
  - DST-PORT,30021,ğŸ¯ 
  - DST-PORT,30190,ğŸ¯ 
  - DST-PORT,30220,ğŸ¯ 
  - IP-CIDR,8.214.32.0/24,ğŸ¯ 
  - IP-CIDR,23.248.168.0/21,ğŸ¯ 
  - IP-CIDR,34.101.143.0/24,ğŸ¯ 
  - IP-CIDR,101.78.11.0/24,ğŸ¯ 
  - IP-CIDR,103.16.137.0/24,ğŸ¯ 
  - IP-CIDR,103.96.77.0/24,ğŸ¯ 
  - IP-CIDR,103.104.168.250/24,ğŸ¯ 
  - IP-CIDR,103.104.168.0/24,ğŸ¯ 
  - IP-CIDR,103.152.14.0/24,ğŸ¯ 
  - IP-CIDR,107.155.39.0/24,ğŸ¯ 
  - IP-CIDR,119.81.0.0/17,ğŸ¯ 
  - IP-CIDR,128.1.87.0/24,ğŸ¯ 
  - IP-CIDR,129.227.0.0/16,ğŸ¯ 
  - IP-CIDR,159.122.133.0/24,ğŸ¯ 
  - IP-CIDR,161.202.192.0/18,ğŸ¯ 
  - IP-CIDR,164.52.0.0/17,ğŸ¯ 
  - IP-CIDR,168.1.193.0/24,ğŸ¯ 
  - IP-CIDR,169.46.132.0/24,ğŸ¯ 
  - IP-CIDR,169.56.0.0/16,ğŸ¯ 
  - IP-CIDR,185.23.183.0/24,ğŸ¯ 
  - IP-CIDR,192.169.113.0/24,ğŸ¯ 
  - IP-CIDR,193.118.34.0/24,ğŸ¯ 
  - MATCH,ğŸš€
